import robot
import requests as req
import time
import i2c
robot.eyesforward()
time.sleep(0.35)
robot.eyesup()
time.sleep(0.35)
i2c.forward()
time.sleep(0.7)
i2c.stop()
time.sleep(0.25)
i2c.back()
time.sleep(0.7)
i2c.stop()
time.sleep(3)
robot.eyesforward()
time.sleep(0.35)
robot.eyesleft()
time.sleep(0.35)
robot.eyesforward()
time.sleep(0.35)
robot.eyesup()
time.sleep(0.35)
robot.eyesright()
time.sleep(0.35)
robot.eyesforward()
time.sleep(0.35)
robot.wave()
